# 1. 开启鼠标支持！（可以用鼠标滚轮上下翻看历史，可以直接用鼠标拖动分屏大小、点击切换窗口）
set -g mouse on

# 2. 更直观的分屏快捷键：
# 按 Ctrl+b 然后按 | (竖线) -> 左右垂直分屏
# 按 Ctrl+b 然后按 - (减号) -> 上下水平分屏
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# 3. 开启终端 256 真实色彩支持（让 Vim 配色更好看）
set -g default-terminal "screen-256color"

# 4. 消除按键延迟（让按 Esc 切换模式更利索）
set -s escape-time 0
